 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/maintenance_logs", type: :request do
  
  # MaintenanceLog. As you add validations to MaintenanceLog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MaintenanceLog.create! valid_attributes
      get maintenance_logs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      maintenance_log = MaintenanceLog.create! valid_attributes
      get maintenance_log_url(maintenance_log)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_maintenance_log_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      maintenance_log = MaintenanceLog.create! valid_attributes
      get edit_maintenance_log_url(maintenance_log)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MaintenanceLog" do
        expect {
          post maintenance_logs_url, params: { maintenance_log: valid_attributes }
        }.to change(MaintenanceLog, :count).by(1)
      end

      it "redirects to the created maintenance_log" do
        post maintenance_logs_url, params: { maintenance_log: valid_attributes }
        expect(response).to redirect_to(maintenance_log_url(MaintenanceLog.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MaintenanceLog" do
        expect {
          post maintenance_logs_url, params: { maintenance_log: invalid_attributes }
        }.to change(MaintenanceLog, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post maintenance_logs_url, params: { maintenance_log: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested maintenance_log" do
        maintenance_log = MaintenanceLog.create! valid_attributes
        patch maintenance_log_url(maintenance_log), params: { maintenance_log: new_attributes }
        maintenance_log.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the maintenance_log" do
        maintenance_log = MaintenanceLog.create! valid_attributes
        patch maintenance_log_url(maintenance_log), params: { maintenance_log: new_attributes }
        maintenance_log.reload
        expect(response).to redirect_to(maintenance_log_url(maintenance_log))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        maintenance_log = MaintenanceLog.create! valid_attributes
        patch maintenance_log_url(maintenance_log), params: { maintenance_log: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested maintenance_log" do
      maintenance_log = MaintenanceLog.create! valid_attributes
      expect {
        delete maintenance_log_url(maintenance_log)
      }.to change(MaintenanceLog, :count).by(-1)
    end

    it "redirects to the maintenance_logs list" do
      maintenance_log = MaintenanceLog.create! valid_attributes
      delete maintenance_log_url(maintenance_log)
      expect(response).to redirect_to(maintenance_logs_url)
    end
  end
end
